//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace task_4_Gui_Implementation
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int Ticketid { get; set; }
        public Nullable<int> Customerid { get; set; }
        public Nullable<System.DateTime> DateOfJourney { get; set; }
        public Nullable<int> Flightid { get; set; }
        public Nullable<int> Seatno { get; set; }
    }
}
